### ISSUE TITLE
You need node

### ISSUE THREAD

**Issue by drj11** [ISA-tools/isa-explorer#72]
It may seem obvious, but you don't say that you need `node`.

(the joys of installing on a machine where I'm not doing node development).

Perhaps surprisingly (to me), installing `npm` doesn't install `node`.

**Comment by drj11** [comment]
Specifically, you need a command called `node`.

On my Ubuntu 16.0.4.3 LTS laptop, installing `npm` does in fact install node, using a `nodejs` package. But the executable binary it installs is called `nodejs`.

To get the `node` command, you need to install the `nodejs-legacy` package, which installs a symlink from `/usr/bin/node` to `usr/bin/nodejs`. Thanks Ubuntu.

**Comment by Zigur** [comment]
Hi @drj11 thanks for the feedback, I have updated the README, which might need further changes.
npm comes together with Node so installing node on Ubuntu you do not need other package. In the past npm used to be a separate package but that has been deprecated, hence do not trust that package on any *nix system

**Comment by drj11** [comment]
For The Record, the Debian package for Ubuntu 16.04 installed Node 4.something;

I gritted my teeth and installed `nvm` and used that to install Node 6.something and that seems to be fine.

**Comment by agbeltran** [comment]
thanks @drj11 for letting us know; it would be great if you want to help contributing some documentation on those steps

**Comment by agbeltran** [comment]
This issue was resolved by documenting the dependencies in the README file. Re-open if anything is missing. Thanks
