### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by AlasdairGray** [ISA-tools/isa-explorer#73]
Currently seeing the following
![screen shot 2018-06-13 at 11 54 52](https://user-images.githubusercontent.com/1141265/41347139-a493fca8-6f00-11e8-94d4-2aa77eb0bfbb.png)

**Comment by agbeltran** [comment]
Thank you, yes, we are aware and are working on fixing the issues with the VM.

**Comment by AlasdairGray** [comment]
Great. Good luck getting it fixed.

**Comment by agbeltran** [comment]
@AlasdairGray - apologies for not communicating it earlier, but the site was back up shortly after you reported the problem
