### ISSUE TITLE
Display bug on scientific data

### ISSUE THREAD

**Issue by yvanlebras** [ISA-tools/isa-explorer#74]
Dear isa-explorer team,

It seems there is a bug on the display of titles on the scientific-data isa-explorer site as you can see on this screenshot:

![isaexplorer](https://user-images.githubusercontent.com/7910679/42549064-8453dc8a-84ca-11e8-943a-89a9548d8e3d.PNG)

**Comment by proccaserra** [comment]
Hello @yvanlebras , can you give more details about the nature of the bug?
I suppose you are accessing the following: http://scientificdata.isa-explorer.org/sdata20167

What is the behaviour you would expect vs what is that you get?

Or is it about the 'squares' before and after each line ? I am seeing something different on chrome and safari. You are using Firefox, am i correct with this? seems a minor css/html rendering issue. we'll investigate

thx for reporting

**Comment by agbeltran** [comment]
@yvanlebras this is fixed now (tested in Firefox, Chrome and Safari), thanks for the report (and apologies for the delay in getting it fixed)
